version: '2'

services:
  app:
    container_name: node-slackbot
    image: node:latest
    volumes:
      - ".:/slackbot"
    working_dir: /slackbot
    tty: true
    stdin_open: true
  mongodata:
    image: mongo:latest
    volumes:
      - /data/db
    command: --break-mongo
  mongo:
    image: mongo:latest
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
    command: --smallfiles --rest --auth
