version: '2'

services:
  app:
    container_name: node-wardubot
    image: node:latest
    environment:
      - SLACKBOT_TOKEN=xoxb-147510149990-8gMO94IOGO4U48EXLSipbvq4
      - CLOUDINARY_NAME=doj3kuv7g
      - CLOUDINARY_KEY=587251674318611
      - CLOUDINARY_SECRET=lrQYj59WR4nBLeqVybzYcLImvL0
    volumes:
      - ".:/wardubot" 
    working_dir: /wardubot
    command: bash -c "npm install &&  npm install -g forever && forever start app.js"
    tty: true
    stdin_open: true
